"""
Sample/demo data for testing when Yahoo Finance API is unavailable.
Contains realistic mock results matching the screener output format.
"""

SAMPLE_RESULTS = [
    {
        "ticker": "AMZN",
        "name": "Amazon.com Inc",
        "sector": "Consumer Cyclical",
        "industry": "Internet Retail",
        "market_cap": 1920000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "NEUTRAL",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 198.45,
        "price_ma": 191.30,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 14.22,
        "price_change_pct": 5.12,
    },
    {
        "ticker": "META",
        "name": "Meta Platforms Inc",
        "sector": "Communication Services",
        "industry": "Internet Content & Information",
        "market_cap": 1450000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "WEAK BEAR",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 542.80,
        "price_ma": 530.15,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 38.50,
        "price_change_pct": 3.87,
    },
    {
        "ticker": "JPM",
        "name": "JPMorgan Chase & Co",
        "sector": "Financial Services",
        "industry": "Banks - Diversified",
        "market_cap": 620000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "STRONG BEAR",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 218.90,
        "price_ma": 210.45,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 12.80,
        "price_change_pct": 4.55,
    },
    {
        "ticker": "UNH",
        "name": "UnitedHealth Group Inc",
        "sector": "Healthcare",
        "industry": "Healthcare Plans",
        "market_cap": 480000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "NEUTRAL",
        "months_in_weak_bull": 2,
        "entry_date": "2026-02-01",
        "current_price": 532.10,
        "price_ma": 520.80,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 28.40,
        "price_change_pct": 2.18,
    },
    {
        "ticker": "V",
        "name": "Visa Inc",
        "sector": "Financial Services",
        "industry": "Credit Services",
        "market_cap": 580000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "NEUTRAL",
        "months_in_weak_bull": 2,
        "entry_date": "2026-02-01",
        "current_price": 298.55,
        "price_ma": 290.20,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 15.60,
        "price_change_pct": 1.85,
    },
    {
        "ticker": "COST",
        "name": "Costco Wholesale Corp",
        "sector": "Consumer Defensive",
        "industry": "Discount Stores",
        "market_cap": 390000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "WEAK BEAR",
        "months_in_weak_bull": 2,
        "entry_date": "2026-02-01",
        "current_price": 892.30,
        "price_ma": 875.10,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 42.15,
        "price_change_pct": 1.42,
    },
    {
        "ticker": "LLY",
        "name": "Eli Lilly and Company",
        "sector": "Healthcare",
        "industry": "Drug Manufacturers",
        "market_cap": 720000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "STRONG BEAR",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 785.20,
        "price_ma": 768.90,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 52.30,
        "price_change_pct": 6.22,
    },
    {
        "ticker": "AMD",
        "name": "Advanced Micro Devices",
        "sector": "Technology",
        "industry": "Semiconductors",
        "market_cap": 240000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "WEAK BEAR",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 164.75,
        "price_ma": 158.20,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 12.45,
        "price_change_pct": 7.33,
    },
    {
        "ticker": "NFLX",
        "name": "Netflix Inc",
        "sector": "Communication Services",
        "industry": "Entertainment",
        "market_cap": 310000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "NEUTRAL",
        "months_in_weak_bull": 3,
        "entry_date": "2026-01-01",
        "current_price": 725.40,
        "price_ma": 710.50,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 35.80,
        "price_change_pct": 0.95,
    },
    {
        "ticker": "CAT",
        "name": "Caterpillar Inc",
        "sector": "Industrials",
        "industry": "Farm & Heavy Construction Machinery",
        "market_cap": 170000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "STRONG BEAR",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 342.60,
        "price_ma": 330.15,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 18.90,
        "price_change_pct": 4.88,
    },
    {
        "ticker": "GS",
        "name": "Goldman Sachs Group",
        "sector": "Financial Services",
        "industry": "Capital Markets",
        "market_cap": 160000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "NEUTRAL",
        "months_in_weak_bull": 2,
        "entry_date": "2026-02-01",
        "current_price": 478.30,
        "price_ma": 465.90,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 24.60,
        "price_change_pct": 2.75,
    },
    {
        "ticker": "ADBE",
        "name": "Adobe Inc",
        "sector": "Technology",
        "industry": "Software - Infrastructure",
        "market_cap": 220000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "WEAK BEAR",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 498.70,
        "price_ma": 485.20,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 28.90,
        "price_change_pct": 5.15,
    },
    {
        "ticker": "PG",
        "name": "Procter & Gamble Co",
        "sector": "Consumer Defensive",
        "industry": "Household & Personal Products",
        "market_cap": 380000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "NEUTRAL",
        "months_in_weak_bull": 3,
        "entry_date": "2026-01-01",
        "current_price": 168.45,
        "price_ma": 164.80,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 7.50,
        "price_change_pct": 0.62,
    },
    {
        "ticker": "DE",
        "name": "Deere & Company",
        "sector": "Industrials",
        "industry": "Farm & Heavy Construction Machinery",
        "market_cap": 120000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "STRONG BEAR",
        "months_in_weak_bull": 1,
        "entry_date": "2026-03-01",
        "current_price": 415.80,
        "price_ma": 400.25,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 22.10,
        "price_change_pct": 5.80,
    },
    {
        "ticker": "ISRG",
        "name": "Intuitive Surgical Inc",
        "sector": "Healthcare",
        "industry": "Medical Instruments & Supplies",
        "market_cap": 180000000000,
        "current_bias": "WEAK BULL",
        "previous_bias": "NEUTRAL",
        "months_in_weak_bull": 2,
        "entry_date": "2026-02-01",
        "current_price": 512.90,
        "price_ma": 498.30,
        "cvd_vs_ma": "ABOVE",
        "price_vs_ma": "ABOVE",
        "is_chop": False,
        "atr": 30.20,
        "price_change_pct": 2.30,
    },
]
